# Generated by Django 3.2.16 on 2023-01-09 06:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado_em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('ativo', models.BooleanField(default=True)),
                ('nome_plataforma', models.CharField(max_length=128, verbose_name='Nome da Plataforma')),
                ('taxa_plataforma', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Anúcio',
                'verbose_name_plural': 'Anúncios',
            },
        ),
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado_em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.CharField(blank=True, default=uuid.uuid4, max_length=128, null=True, unique=True, verbose_name='Codigo do Imóvel')),
                ('limite_hospede', models.IntegerField(default=0, verbose_name='Limite de Hóspedes')),
                ('qtde_banheiro', models.IntegerField(default=0, verbose_name='Quantide de Banheiros')),
                ('animais', models.BooleanField(default=False)),
                ('valor_limpeza', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('endereco', models.CharField(blank=True, max_length=256, null=True, verbose_name='Endereço do Imóvel')),
            ],
            options={
                'verbose_name': 'Imóvel',
                'verbose_name_plural': 'Imóveis',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado_em')),
                ('deletado_em', models.DateTimeField(blank=True, null=True, verbose_name='Deletado em')),
                ('ativo', models.BooleanField(default=True)),
                ('codigo', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('check_in', models.DateTimeField(blank=True, default=None, null=True)),
                ('check_out', models.DateTimeField(blank=True, default=None, null=True)),
                ('preco', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('num_hospedes', models.IntegerField(default=0)),
                ('anucio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reserva_anucio', to='core.anuncio', verbose_name='Reserva')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
            },
        ),
        migrations.AddField(
            model_name='anuncio',
            name='imovel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anucio_imovel', to='core.imovel', verbose_name='Imóvel'),
        ),
    ]
